### ISSUE TITLE
(Not an issue) Help for okhttp cookie managing when doing a POST

### ISSUE THREAD

**Issue by Joyliu290** [benawad/Munchy#2]
Hi Ben, sorry to bug you again...
This is not an issue but I thought posting this might reach you faster.
Since you have used Asynctask and okhttp for Munchy, I thought maybe you can shed some light on how to pass a web cookie name and value alongside with a POST using okhttp. 

Some more background:
I need to pass the cookie that I got from website A, to website B thru a POST. I received the cookie from website A thru a GET and have stored the name and value of the cookie into 2 string variables. However I have tried countless ways on how to pass the same cookie to website B via a POST but nothing has worked out so far :( My call to website B just says "call failed, no session", meaning that it didn't recognize my call since cookie did not get through. 

Passing this cookie is crucial to my current project and you are the first  one that I thought of after many tries at debugging this problem. 

Thank you so much, and I look forward to your response at this issue!

**Comment by benawad** [comment]
Hey Joy, you're not bugging me at all. Feel free to ask questions whenever :)

Have you tried using cookie manager https://stackoverflow.com/questions/24263921/how-to-implement-cookie-handling-on-android-using-okhttp

**Comment by Joyliu290** [comment]
Hey Ben, I have tried to use the cookie manager, but somehow (I'm quite new to okhttp) it doesn't pass the cookie when I do a POST. From these stackoverflow pages I think I understood a bit on how cookie manager works but I'm not entirely sure how to link this cookie manager to a POST call so that it can pass the cookie when I do a POST. 

Another option I have looked at is to add ".addHeader(cookieName, cookieValue)" to the Request (okhttp provides this option). However for some reason this doesn't add the header to my POST call...below is my code as an example in case it sounds too complicated: 

                  OkHttpClient quoteClient = new OkHttpClient();
                   RequestBody postData = new FormBody.Builder()
                           .add("example","example")                           
                           .build();

                    Request quoteRequest = new Request.Builder()
                            .url("example.com")
                            .post(postData)
                            .addHeader(cookieName,cookieValue)
                            .build();

                    Log.v("headers",quoteRequest.headers().toString());  //here to check if header is added, and it is added

                    quoteClient.newCall(quoteRequest).enqueue(new Callback() {
                        @Override
                        public void onFailure(Call call, IOException e) {
                            Log.v("Fail","Fail");
                        }

                        @Override
                        public void onResponse(Call call, Response response) throws IOException {
                            //String result = response.body().string();
                            String resultHeader = response.headers().toString(); //but here the header I just added somehow does not appear in the Log
                            Log.v("quote",resultHeader);
                        }
                    });

I made 2 comments in the above code and that was where things went wrong. This is actually my code to do a POST and I would definitely appreciated if you can teach me how to link cookie manager (or other ways of handling cookie) to my POST call.

Thank you so much for taking your time to solve this! (in case you were wondering, I did bring up this issue of ".addHeader()" to OkHttp github, but they closed it saying I should ask on stackoverflow :( Thought I might get an answer faster by directing asking you)

**Comment by benawad** [comment]
Your code looks like it would correctly pass the header for your request. If it's not working, the server may be expecting the header in a different way. What server are you making a request to?

onResponse is what the server sends back, so you shouldn't expect to see the header you added there (unless the server was supposed to give you a header back).

**Comment by Joyliu290** [comment]
Hmm thanks for bringing this up...I never thought the server would be expecting the cookie in other ways other than adding it. The server is redis but I'll try cracking at this issue myself first, but now at a different direction, and I'll keep you posted if I still can't solve it. 

Thanks again Ben!

**Comment by benawad** [comment]
Ok, sounds good.

**Comment by Joyliu290** [comment]
Hey Ben, turns out there is nothing wrong with .addHeader...I digged around and realized that cookie name is supposed to be "Cookie". Thanks for introducing me to OkHttp and your help on this!

**Comment by benawad** [comment]
Glad you figured it out.
